# Generated by Django 4.1.2 on 2022-10-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_ad', models.DateTimeField(auto_now_add=True, verbose_name='Updated date')),
                ('status', models.TextField(choices=[('activ', 'activ'), ('blocked', 'blocked')], default='activ', max_length=100, verbose_name='Status')),
            ],
        ),
    ]
