# Generated by Django 4.1.2 on 2023-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated_ad',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
